apiVersion: apps/v1
kind: Deployment
metadata:
  name: whalestream-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whalestream-api
  template:
    metadata:
      labels:
        app: whalestream-api
    spec:
      containers:
      - name: whalestream-api
        image: dungxtd/whalestream-api:0.1.2
        command: ["yarn", "start:prod"]
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: ENV
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: TZ
        - name: UMASK_SET
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: UMASK_SET
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: PGID
        - name: JACKETT_AUTOMATIC_SEARCH_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: JACKETT_AUTOMATIC_SEARCH_TIMEOUT
        - name: JACKETT_MANUAL_SEARCH_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: JACKETT_MANUAL_SEARCH_TIMEOUT
        - name: LIBRARY_MOVIES_FOLDER_NAME
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: LIBRARY_MOVIES_FOLDER_NAME
        - name: LIBRARY_TV_SHOWS_FOLDER_NAME
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: LIBRARY_TV_SHOWS_FOLDER_NAME
        - name: DEBUG_REDIS
          valueFrom:
            configMapKeyRef:
              name: whalestream-api-config
              key: DEBUG_REDIS
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: whalestream-api-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: whalestream-api-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: whalestream-api-secret
              key: POSTGRES_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: whalestream-api-secret
              key: REDIS_PASSWORD
        volumeMounts:
        - name: library
          mountPath: /usr/library
      volumes:
      - name: library
        hostPath:
          path: /path/to/your/library  # Replace this with the correct path on your node
