version: "3.8"
services:
  # blog:
  #   image: dungxtd/whalelog:0.1.7
  #   ports:
  #     - 82:3000
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 8089:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    # depends_on:
    #   - blog