apiVersion: v1
kind: Service
metadata:
  name: whalestream-api-service
spec:
  selector:
    app: whalestream-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: whale-bobar-web-service
spec:
  selector:
    app: whale-bobar-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: whalelog-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: whalelog
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: whalestream-landing-service
spec:
  selector:
    app: whalestream-landing
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
  
---

apiVersion: v1
kind: Service
metadata:
  name: whale-py-service
spec:
  selector:
    app: whale-py
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer